server:
  port: 8084
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/