server:
  port: 8081
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  webuni:
    tokenlib:
      keypaths:
        public: /Users/RAP/certificates/public.pem
spring:
  datasource:
    password: Delfin2x21
    url: jdbc:postgresql://localhost:5432/webshop-catalog
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
  flyway:
    baseline-on-migrate: true