server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  webuni:
    tokenlib:
      keypaths:
        public: /Users/RAP/certificates/public.pem
spring:
  cloud:
    gateway:
      routes:
      - id: catalog
        uri: lb://catalog
        predicates:
        - Path=/catalog/**
        filters:
        - RewritePath=/catalog(?<segment>/?.*), /api$\{segment}
      - id: order
        uri: lb://order
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order(?<segment>/?.*), /api$\{segment}
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user(?<segment>/?.*), /api$\{segment}
